
server:
  port: 9192

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9191/auth/realms/kofax/protocol/openid-connect/certs

kofax:
  local:
    keycloakUrl: http://localhost:9191/auth
    adminRealm: master
    username: admin
    password: admin
    adminCliendId: admin-cli
    realm: demo
    outputDir: C:\\KapowWork\\

